
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action openAction1;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action saveAsAction;
	
	private global::Gtk.Action goDownAction;
	
	private global::Gtk.Action goUpAction;
	
	private global::Gtk.Action addAction;
	
	private global::Gtk.Action deleteAction;
	
	private global::Gtk.VBox vbox_main;
	
	private global::Gtk.MenuBar menubar_main;
	
	private global::Gtk.Toolbar toolbar2;
	
	private global::Gtk.Notebook notebook_main;
	
	private global::Gtk.VPaned vpaned1;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", null, null, "gtk-open");
		w1.Add (this.openAction1, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, null, "gtk-save-as");
		w1.Add (this.saveAsAction, null);
		this.goDownAction = new global::Gtk.Action ("goDownAction", null, null, "gtk-go-down");
		w1.Add (this.goDownAction, null);
		this.goUpAction = new global::Gtk.Action ("goUpAction", null, null, "gtk-go-up");
		w1.Add (this.goUpAction, null);
		this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
		w1.Add (this.addAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", null, null, "gtk-delete");
		w1.Add (this.deleteAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("CalGen");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox_main = new global::Gtk.VBox ();
		this.vbox_main.Name = "vbox_main";
		// Container child vbox_main.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar_main'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'/></menubar></ui>");
		this.menubar_main = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar_main")));
		this.menubar_main.Name = "menubar_main";
		this.vbox_main.Add (this.menubar_main);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox_main [this.menubar_main]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox_main.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='openAction1' action='openAction1'/><toolitem name='saveAction' action='saveAction'/><toolitem name='saveAsAction' action='saveAsAction'/><toolitem name='goDownAction' action='goDownAction'/><toolitem name='goUpAction' action='goUpAction'/><toolitem name='addAction' action='addAction'/><toolitem name='deleteAction' action='deleteAction'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.vbox_main.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox_main [this.toolbar2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox_main.Gtk.Box+BoxChild
		this.notebook_main = new global::Gtk.Notebook ();
		this.notebook_main.CanFocus = true;
		this.notebook_main.Name = "notebook_main";
		this.notebook_main.CurrentPage = 0;
		// Container child notebook_main.Gtk.Notebook+NotebookChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 164;
		this.notebook_main.Add (this.vpaned1);
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Variable");
		this.notebook_main.SetTabLabel (this.vpaned1, this.label5);
		this.label5.ShowAll ();
		// Notebook tab
		global::Gtk.Label w5 = new global::Gtk.Label ();
		w5.Visible = true;
		this.notebook_main.Add (w5);
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Array");
		this.notebook_main.SetTabLabel (w5, this.label6);
		this.label6.ShowAll ();
		// Notebook tab
		global::Gtk.Label w6 = new global::Gtk.Label ();
		w6.Visible = true;
		this.notebook_main.Add (w6);
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Curve");
		this.notebook_main.SetTabLabel (w6, this.label9);
		this.label9.ShowAll ();
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this.notebook_main.Add (w7);
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Table");
		this.notebook_main.SetTabLabel (w7, this.label7);
		this.label7.ShowAll ();
		// Notebook tab
		global::Gtk.Label w8 = new global::Gtk.Label ();
		w8.Visible = true;
		this.notebook_main.Add (w8);
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Map");
		this.notebook_main.SetTabLabel (w8, this.label8);
		this.label8.ShowAll ();
		// Notebook tab
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.Visible = true;
		this.notebook_main.Add (w9);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Axis");
		this.notebook_main.SetTabLabel (w9, this.label4);
		this.label4.ShowAll ();
		// Notebook tab
		global::Gtk.Label w10 = new global::Gtk.Label ();
		w10.Visible = true;
		this.notebook_main.Add (w10);
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Computing Method");
		this.notebook_main.SetTabLabel (w10, this.label3);
		this.label3.ShowAll ();
		// Notebook tab
		global::Gtk.Label w11 = new global::Gtk.Label ();
		w11.Visible = true;
		this.notebook_main.Add (w11);
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Structure");
		this.notebook_main.SetTabLabel (w11, this.label1);
		this.label1.ShowAll ();
		// Notebook tab
		global::Gtk.Label w12 = new global::Gtk.Label ();
		w12.Visible = true;
		this.notebook_main.Add (w12);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Unit");
		this.notebook_main.SetTabLabel (w12, this.label2);
		this.label2.ShowAll ();
		this.vbox_main.Add (this.notebook_main);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox_main [this.notebook_main]));
		w13.Position = 2;
		this.Add (this.vbox_main);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 890;
		this.DefaultHeight = 462;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
