
// This file has been generated by the GUI designer. Do not modify.
namespace SHex
{
	public partial class MemBlockView
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TreeView treeviewMemBlcs;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SHex.MemBlockView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "SHex.MemBlockView";
			// Container child SHex.MemBlockView.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.treeviewMemBlcs = new global::Gtk.TreeView ();
			this.treeviewMemBlcs.CanFocus = true;
			this.treeviewMemBlcs.Name = "treeviewMemBlcs";
			this.treeviewMemBlcs.Reorderable = true;
			this.scrolledwindow1.Add (this.treeviewMemBlcs);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
