//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AML.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace a2mlcsharp {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AMLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IAMLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.a2ml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitA2ml([NotNull] AMLParser.A2mlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration_list([NotNull] AMLParser.Declaration_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] AMLParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_definition([NotNull] AMLParser.Type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] AMLParser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.predefined_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefined_type_name([NotNull] AMLParser.Predefined_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.block_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_definition([NotNull] AMLParser.Block_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.enum_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_type_name([NotNull] AMLParser.Enum_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.enumerator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator_list([NotNull] AMLParser.Enumerator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator([NotNull] AMLParser.EnumeratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.struct_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_type_name([NotNull] AMLParser.Struct_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.struct_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_member_list([NotNull] AMLParser.Struct_member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.struct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_member([NotNull] AMLParser.Struct_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember([NotNull] AMLParser.MemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.array_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_specifier([NotNull] AMLParser.Array_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.taggedstruct_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_type_name([NotNull] AMLParser.Taggedstruct_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.taggedstruct_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_member_list([NotNull] AMLParser.Taggedstruct_member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.taggedstruct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_member([NotNull] AMLParser.Taggedstruct_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.taggedstruct_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_definition([NotNull] AMLParser.Taggedstruct_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.taggedunion_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedunion_type_name([NotNull] AMLParser.Taggedunion_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.taggedunion_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedunion_member_list([NotNull] AMLParser.Taggedunion_member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.tagged_union_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagged_union_member([NotNull] AMLParser.Tagged_union_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] AMLParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTag([NotNull] AMLParser.TagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] AMLParser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AMLParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] AMLParser.ConstantContext context);
}
} // namespace a2mlcsharp
