//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from A2L.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace a2lcsharp {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="A2LParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IA2LVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.a2ml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitA2ml([NotNull] A2LParser.A2mlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] A2LParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_definition([NotNull] A2LParser.Type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] A2LParser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.predefined_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefined_type_name([NotNull] A2LParser.Predefined_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.block_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_definition([NotNull] A2LParser.Block_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.enum_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum_type_name([NotNull] A2LParser.Enum_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.enumerator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator_list([NotNull] A2LParser.Enumerator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator([NotNull] A2LParser.EnumeratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.struct_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_type_name([NotNull] A2LParser.Struct_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.struct_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_member_list([NotNull] A2LParser.Struct_member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.struct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_member([NotNull] A2LParser.Struct_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember([NotNull] A2LParser.MemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.array_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_specifier([NotNull] A2LParser.Array_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.taggedstruct_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_type_name([NotNull] A2LParser.Taggedstruct_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.taggedstruct_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_member_list([NotNull] A2LParser.Taggedstruct_member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.taggedstruct_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_member([NotNull] A2LParser.Taggedstruct_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.taggedstruct_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedstruct_definition([NotNull] A2LParser.Taggedstruct_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.taggedunion_type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedunion_type_name([NotNull] A2LParser.Taggedunion_type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.taggedunion_member_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaggedunion_member_list([NotNull] A2LParser.Taggedunion_member_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.tagged_union_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTagged_union_member([NotNull] A2LParser.Tagged_union_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] A2LParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTag([NotNull] A2LParser.TagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] A2LParser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] A2LParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.a2l"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitA2l([NotNull] A2LParser.A2lContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.a2ml_ver"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitA2ml_ver([NotNull] A2LParser.A2ml_verContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.addr_epk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddr_epk([NotNull] A2LParser.Addr_epkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.alignment_byte"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignment_byte([NotNull] A2LParser.Alignment_byteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.alignment_float32_ieee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignment_float32_ieee([NotNull] A2LParser.Alignment_float32_ieeeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.alignment_float64_ieee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignment_float64_ieee([NotNull] A2LParser.Alignment_float64_ieeeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.alignment_int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignment_int64([NotNull] A2LParser.Alignment_int64Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.alignment_long"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignment_long([NotNull] A2LParser.Alignment_longContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.alignment_word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignment_word([NotNull] A2LParser.Alignment_wordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] A2LParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.annotation_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation_label([NotNull] A2LParser.Annotation_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.annotation_origin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation_origin([NotNull] A2LParser.Annotation_originContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.annotation_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation_text([NotNull] A2LParser.Annotation_textContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.array_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_size([NotNull] A2LParser.Array_sizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.asap2_ver"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsap2_ver([NotNull] A2LParser.Asap2_verContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_descr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_descr([NotNull] A2LParser.Axis_descrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_pts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_pts([NotNull] A2LParser.Axis_ptsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_pts_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_pts_ref([NotNull] A2LParser.Axis_pts_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_pts_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_pts_x([NotNull] A2LParser.Axis_pts_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_pts_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_pts_y([NotNull] A2LParser.Axis_pts_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_pts_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_pts_z([NotNull] A2LParser.Axis_pts_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_pts_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_pts_4([NotNull] A2LParser.Axis_pts_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_pts_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_pts_5([NotNull] A2LParser.Axis_pts_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.axis_rescale_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_rescale_x([NotNull] A2LParser.Axis_rescale_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.bit_mask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBit_mask([NotNull] A2LParser.Bit_maskContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.bit_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBit_operation([NotNull] A2LParser.Bit_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.byte_order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitByte_order([NotNull] A2LParser.Byte_orderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.calibration_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalibration_access([NotNull] A2LParser.Calibration_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.calibration_handle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalibration_handle([NotNull] A2LParser.Calibration_handleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.calibration_handle_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalibration_handle_text([NotNull] A2LParser.Calibration_handle_textContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.calibration_method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalibration_method([NotNull] A2LParser.Calibration_methodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.characteristic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacteristic([NotNull] A2LParser.CharacteristicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.coeffs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCoeffs([NotNull] A2LParser.CoeffsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.coeffs_linear"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCoeffs_linear([NotNull] A2LParser.Coeffs_linearContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.comparison_quantity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_quantity([NotNull] A2LParser.Comparison_quantityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.compu_method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompu_method([NotNull] A2LParser.Compu_methodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.compu_tab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompu_tab([NotNull] A2LParser.Compu_tabContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.compu_tab_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompu_tab_ref([NotNull] A2LParser.Compu_tab_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.compu_vtab"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompu_vtab([NotNull] A2LParser.Compu_vtabContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.compu_vtab_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompu_vtab_range([NotNull] A2LParser.Compu_vtab_rangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.cpu_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCpu_type([NotNull] A2LParser.Cpu_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.curve_axis_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCurve_axis_ref([NotNull] A2LParser.Curve_axis_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.customer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomer([NotNull] A2LParser.CustomerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.customer_no"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomer_no([NotNull] A2LParser.Customer_noContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.data_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_size([NotNull] A2LParser.Data_sizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.def_characteristic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDef_characteristic([NotNull] A2LParser.Def_characteristicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.default_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_value([NotNull] A2LParser.Default_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.default_value_numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_value_numeric([NotNull] A2LParser.Default_value_numericContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.dependent_characteristic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependent_characteristic([NotNull] A2LParser.Dependent_characteristicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.deposit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeposit([NotNull] A2LParser.DepositContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.discrete"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiscrete([NotNull] A2LParser.DiscreteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.display_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisplay_identifier([NotNull] A2LParser.Display_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.dist_op_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDist_op_x([NotNull] A2LParser.Dist_op_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.dist_op_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDist_op_y([NotNull] A2LParser.Dist_op_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.dist_op_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDist_op_z([NotNull] A2LParser.Dist_op_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.dist_op_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDist_op_4([NotNull] A2LParser.Dist_op_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.dist_op_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDist_op_5([NotNull] A2LParser.Dist_op_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ecu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEcu([NotNull] A2LParser.EcuContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ecu_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEcu_address([NotNull] A2LParser.Ecu_addressContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ecu_address_extension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEcu_address_extension([NotNull] A2LParser.Ecu_address_extensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ecu_calibration_offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEcu_calibration_offset([NotNull] A2LParser.Ecu_calibration_offsetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.epk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEpk([NotNull] A2LParser.EpkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.error_mask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError_mask([NotNull] A2LParser.Error_maskContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.extended_limits"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtended_limits([NotNull] A2LParser.Extended_limitsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_axis_par"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_axis_par([NotNull] A2LParser.Fix_axis_parContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_axis_par_dist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_axis_par_dist([NotNull] A2LParser.Fix_axis_par_distContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_axis_par_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_axis_par_list([NotNull] A2LParser.Fix_axis_par_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_no_axis_pts_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_no_axis_pts_x([NotNull] A2LParser.Fix_no_axis_pts_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_no_axis_pts_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_no_axis_pts_y([NotNull] A2LParser.Fix_no_axis_pts_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_no_axis_pts_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_no_axis_pts_z([NotNull] A2LParser.Fix_no_axis_pts_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_no_axis_pts_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_no_axis_pts_4([NotNull] A2LParser.Fix_no_axis_pts_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fix_no_axis_pts_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFix_no_axis_pts_5([NotNull] A2LParser.Fix_no_axis_pts_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.fnc_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFnc_values([NotNull] A2LParser.Fnc_valuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.formate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormate([NotNull] A2LParser.FormateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula([NotNull] A2LParser.FormulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.formula_inv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula_inv([NotNull] A2LParser.Formula_invContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.frame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame([NotNull] A2LParser.FrameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.frame_measurement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_measurement([NotNull] A2LParser.Frame_measurementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] A2LParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.function_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_list([NotNull] A2LParser.Function_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.function_version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_version([NotNull] A2LParser.Function_versionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup([NotNull] A2LParser.GroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.guard_rails"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuard_rails([NotNull] A2LParser.Guard_railsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeader([NotNull] A2LParser.HeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.identification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentification([NotNull] A2LParser.IdentificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.if_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_data([NotNull] A2LParser.If_dataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclude([NotNull] A2LParser.IncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.in_measurement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_measurement([NotNull] A2LParser.In_measurementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.layout"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout([NotNull] A2LParser.LayoutContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.left_shift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeft_shift([NotNull] A2LParser.Left_shiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.loc_measurement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoc_measurement([NotNull] A2LParser.Loc_measurementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.map_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap_list([NotNull] A2LParser.Map_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.matrix_dim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrix_dim([NotNull] A2LParser.Matrix_dimContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.max_grad"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMax_grad([NotNull] A2LParser.Max_gradContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.max_refresh"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMax_refresh([NotNull] A2LParser.Max_refreshContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.measurement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeasurement([NotNull] A2LParser.MeasurementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.memory_layout"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemory_layout([NotNull] A2LParser.Memory_layoutContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.memory_segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemory_segment([NotNull] A2LParser.Memory_segmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.mod_common"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMod_common([NotNull] A2LParser.Mod_commonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.mod_par"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMod_par([NotNull] A2LParser.Mod_parContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] A2LParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.monotony"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonotony([NotNull] A2LParser.MonotonyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.no_axis_pts_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_axis_pts_x([NotNull] A2LParser.No_axis_pts_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.no_axis_pts_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_axis_pts_y([NotNull] A2LParser.No_axis_pts_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.no_axis_pts_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_axis_pts_z([NotNull] A2LParser.No_axis_pts_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.no_axis_pts_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_axis_pts_4([NotNull] A2LParser.No_axis_pts_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.no_axis_pts_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_axis_pts_5([NotNull] A2LParser.No_axis_pts_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.no_of_A2LNUMerfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_of_A2LNUMerfaces([NotNull] A2LParser.No_of_A2LNUMerfacesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.no_rescale_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNo_rescale_x([NotNull] A2LParser.No_rescale_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] A2LParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.offset_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffset_x([NotNull] A2LParser.Offset_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.offset_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffset_y([NotNull] A2LParser.Offset_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.offset_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffset_z([NotNull] A2LParser.Offset_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.offset_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffset_4([NotNull] A2LParser.Offset_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.offset_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffset_5([NotNull] A2LParser.Offset_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.out_measurement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOut_measurement([NotNull] A2LParser.Out_measurementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.phone_no"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhone_no([NotNull] A2LParser.Phone_noContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.phys_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhys_unit([NotNull] A2LParser.Phys_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.project"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProject([NotNull] A2LParser.ProjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.project_no"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProject_no([NotNull] A2LParser.Project_noContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.read_only"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRead_only([NotNull] A2LParser.Read_onlyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.read_write"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRead_write([NotNull] A2LParser.Read_writeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.record_layout"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_layout([NotNull] A2LParser.Record_layoutContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ref_characteristic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_characteristic([NotNull] A2LParser.Ref_characteristicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ref_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_group([NotNull] A2LParser.Ref_groupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ref_measurement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_measurement([NotNull] A2LParser.Ref_measurementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ref_memory_segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_memory_segment([NotNull] A2LParser.Ref_memory_segmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.ref_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRef_unit([NotNull] A2LParser.Ref_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReserved([NotNull] A2LParser.ReservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.right_shift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRight_shift([NotNull] A2LParser.Right_shiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.rip_addr_w"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRip_addr_w([NotNull] A2LParser.Rip_addr_wContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.rip_addr_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRip_addr_x([NotNull] A2LParser.Rip_addr_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.rip_addr_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRip_addr_y([NotNull] A2LParser.Rip_addr_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.rip_addr_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRip_addr_z([NotNull] A2LParser.Rip_addr_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.rip_addr_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRip_addr_4([NotNull] A2LParser.Rip_addr_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.rip_addr_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRip_addr_5([NotNull] A2LParser.Rip_addr_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] A2LParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.shift_op_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_op_x([NotNull] A2LParser.Shift_op_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.shift_op_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_op_y([NotNull] A2LParser.Shift_op_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.shift_op_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_op_z([NotNull] A2LParser.Shift_op_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.shift_op_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_op_4([NotNull] A2LParser.Shift_op_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.shift_op_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_op_5([NotNull] A2LParser.Shift_op_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.sign_extend"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSign_extend([NotNull] A2LParser.Sign_extendContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.si_exponents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSi_exponents([NotNull] A2LParser.Si_exponentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.src_addr_x"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrc_addr_x([NotNull] A2LParser.Src_addr_xContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.src_addr_y"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrc_addr_y([NotNull] A2LParser.Src_addr_yContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.src_addr_z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrc_addr_z([NotNull] A2LParser.Src_addr_zContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.src_addr_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrc_addr_4([NotNull] A2LParser.Src_addr_4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.src_addr_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrc_addr_5([NotNull] A2LParser.Src_addr_5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.static_record_layout"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatic_record_layout([NotNull] A2LParser.Static_record_layoutContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.status_string_ref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatus_string_ref([NotNull] A2LParser.Status_string_refContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.step_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep_size([NotNull] A2LParser.Step_sizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.sub_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_function([NotNull] A2LParser.Sub_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.sub_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSub_group([NotNull] A2LParser.Sub_groupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.supplier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSupplier([NotNull] A2LParser.SupplierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.symbol_link"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbol_link([NotNull] A2LParser.Symbol_linkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.system_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystem_constant([NotNull] A2LParser.System_constantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnit([NotNull] A2LParser.UnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.unit_conversion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnit_conversion([NotNull] A2LParser.Unit_conversionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.user"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUser([NotNull] A2LParser.UserContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.user_rights"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUser_rights([NotNull] A2LParser.User_rightsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_address([NotNull] A2LParser.Var_addressContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_characteristic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_characteristic([NotNull] A2LParser.Var_characteristicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_criterion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_criterion([NotNull] A2LParser.Var_criterionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_forbidden_comb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_forbidden_comb([NotNull] A2LParser.Var_forbidden_combContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_measurement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_measurement([NotNull] A2LParser.Var_measurementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_naming"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_naming([NotNull] A2LParser.Var_namingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_selection_characteristic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_selection_characteristic([NotNull] A2LParser.Var_selection_characteristicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.var_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_separator([NotNull] A2LParser.Var_separatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.variant_coding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariant_coding([NotNull] A2LParser.Variant_codingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersion([NotNull] A2LParser.VersionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.virtual"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtual([NotNull] A2LParser.VirtualContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="A2LParser.virtual_characteristic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtual_characteristic([NotNull] A2LParser.Virtual_characteristicContext context);
}
} // namespace a2lcsharp
